name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Install package
        run: pip install .

      - name: Run tests (disabled)
        run: echo pytest --cov=showcert --cov-branch --cov-report=xml --cov-report=xml:coverage.xml -s

      - name: debug run pytest
        run: coverage run --source=showcert -m pytest

      - name: Debug run report -m
        run: coverage report -m

      - name: Run tests
        run: coverage xml

      - name: List files
        run: ls -al

      - name: Print coverage.xml
        run: cat coverage.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yaroslaff/showcert

